[project]
name = "jindai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.6.6",
    "bs4>=0.0.2",
    "chardet>=5.2.0",
    "flask>=3.1.2",
    "flask-oidc>=2.4.0",
    "flask-restful>=0.3.10",
    "flask-sqlalchemy>=3.1.1",
    "ipython>=9.9.0",
    "jieba>=0.42.1",
    "opencc-python-reimplemented>=0.1.7",
    "pgvector>=0.4.2",
    "pillow>=12.1.0",
    "psycopg2-binary>=2.9.11",
    "pycryptodome>=3.23.0",
    "pymupdf>=1.26.7",
    "pypdf2>=3.0.1",
    "python-dateutil>=2.9.0.post0",
    "python-iso639>=2025.11.16",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "sqlalchemy>=2.0.45",
    "tqdm>=4.67.1",
    "waitress>=3.0.2",
]

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true
